version: '3.3'
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: my_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped

volumes:
  db_data: